include(FindPkgConfig)
#include(GNUInstallDirs)
set(SUPPORTS_IK True)
if(PKG_CONFIG_FOUND)
    pkg_check_modules(KDL_PARSER kdl_parser)
    pkg_check_modules(TRAC_IK trac_ik_lib)    
    if(NOT KDL_PARSER_FOUND)
       message("-- kdl_parser could not be found. Building without IK support")
       set(SUPPORTS_IK False)
    endif()
    if(NOT TRAC_IK_FOUND)
       message("-- trac_ik_lib could not be found. Building without IK support")
       set(SUPPORTS_IK False)
    endif()   
    if (SUPPORTS_IK)       
       add_definitions(-DSUPPORTS_IK)
       include_directories(${KDL_PARSER_INCLUDE_DIRS})
       link_directories(${KDL_PARSER_LIBRARY_DIRS}) 
       include_directories(${TRAC_IK_INCLUDE_DIRS})
       link_directories(${TRAC_IK_LIBRARY_DIRS})
    endif()
endif()
