min_sensor_dist: .05
self_see_default_padding: .05
self_see_default_scale: 1.0
self_see_links:
  - name: right_forearm_link
  - name: right_wrist_1_link
  - name: right_wrist_2_link
  - name: right_gripper_base_link
